### ISSUE TITLE
Crontab issue: /bin/sh: 1: runp: not found

### ISSUE THREAD

**Issue by JolleJolles** [vascop/runp#3]
When I try to run runp from crontab, e.g. with `50 * * * * runp hello.py test >> hello.txt 2>&1`  it fails and I get the following error: `/bin/sh: 1: runp: not found` How can I fix this?

**Comment by zefno** [comment]
Try to use the exact path of your runp command, it might be in /usr/local/bin for example :
`50 * * * * /usr/local/bin/runp hello.py test >> hello.txt 2>&1
`
To find the exact path : `which runp `

**Comment by JolleJolles** [comment]
Yes I was (many months ago) able to solve it by using the full path `/usr/local/bin/python`. Thanks for a great package!
